In [2]:
import torch

In [3]:
print(torch.__version__)

2.7.1+cu126


In [4]:
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)
print("Device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "N/A")

CUDA available: True
CUDA version: 12.6
Device: NVIDIA GeForce RTX 3050 Ti Laptop GPU


In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [10]:
print(MATRIX.ndim,
MATRIX.shape)

2 torch.Size([2, 2])


In [11]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
print(TENSOR.ndim,TENSOR.shape)

3 torch.Size([1, 3, 3])


In [14]:
### Random tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9802, 0.9636, 0.4443, 0.3720],
        [0.0230, 0.3949, 0.5940, 0.3246],
        [0.6858, 0.6001, 0.4376, 0.0782]])

In [15]:
random_tensor.ndim

2

In [16]:
random__image_size_tensor = torch.rand(size=(224,224,3))
random__image_size_tensor

tensor([[[8.5676e-04, 5.1636e-02, 2.5393e-01],
         [6.5175e-01, 5.4564e-01, 6.6861e-01],
         [3.1979e-01, 9.4656e-01, 9.7969e-01],
         ...,
         [2.2587e-01, 9.2285e-01, 4.6656e-01],
         [8.2297e-01, 2.3719e-02, 5.1079e-02],
         [4.9480e-01, 9.5943e-01, 1.3391e-01]],

        [[2.5713e-01, 9.7241e-01, 1.8110e-01],
         [5.2572e-01, 4.4421e-01, 4.1545e-01],
         [5.6541e-01, 7.4756e-01, 2.4226e-01],
         ...,
         [9.9531e-01, 1.5258e-01, 1.2906e-01],
         [7.0728e-01, 9.5256e-01, 8.3411e-01],
         [7.7798e-01, 8.0504e-01, 8.6076e-01]],

        [[1.1501e-01, 6.5849e-01, 1.8405e-01],
         [7.8495e-01, 5.8768e-01, 7.1203e-01],
         [6.9913e-01, 4.2694e-01, 1.4450e-01],
         ...,
         [5.5066e-01, 2.8826e-01, 3.6618e-01],
         [6.9438e-01, 5.6644e-01, 6.1177e-01],
         [8.1789e-01, 5.4303e-02, 5.3014e-02]],

        ...,

        [[5.1345e-01, 4.8655e-01, 6.9441e-01],
         [8.4951e-01, 6.9521e-01, 6.7354e-01]

In [17]:
random__image_size_tensor.shape , random__image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
#Zeroes and Ones
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(2,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [21]:
ones.dtype , zero.dtype

(torch.float32, torch.float32)

In [33]:
range =  torch.arange(1,11)
range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
#tensors like
ten_zeros = torch.zeros_like(input=range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])